config/routes.rb
Oluprofile::Engine.routes.draw do
  resources :skills
  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/oluprofile/application_record.rb
module Oluprofile
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/oluprofile/skill.rb
module Oluprofile
  class Skill < ApplicationRecord
    belongs_to :user

    validates :name, uniqueness: true, presence: true
    validates :first_used, presence: true, length: { minimum: 4, maximum: 4 }
    validates :last_used, presence: true, length: { minimum: 4, maximum: 4}
    validates :proficiency, presence: true, length: { minimum: 1, maximum: 1 }
    validates_inclusion_of :proficiency, in: 1..5
  end
end

app/models/oluprofile/user.rb
module Oluprofile
  class User < ApplicationRecord
  
    authenticates_with_sorcery!

    has_many :skills
    
    validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
    validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
    validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

    validates :email, uniqueness: true, presence: true
    validates :description, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true
  
  end
end

app/controllers/oluprofile/application_controller.rb
module Oluprofile
  class ApplicationController < ActionController::Base
    before_action :require_login
    protect_from_forgery with: :exception

    def rails_env
      rails_env = !Rails.env.production? ? Rails.env.upcase : nil
    end

    helper_method :rails_env

    private

      def not_authenticated
        redirect_to login_path, alert: "Please login first"
      end

  end
end

app/controllers/oluprofile/skills_controller.rb
module Oluprofile
  class SkillsController < ApplicationController
    before_action :set_skill, only: [:show, :edit, :update, :destroy]

    # GET /skills
    def index
      @skills = current_user.skills.all
    end

    # GET /skills/1
    def show
    end

    # GET /skills/new
    def new
      @skill = current_user.skills.build
    end

    # GET /skills/1/edit
    def edit
    end

    # POST /skills
    def create
      @skill = current_user.skills.build(skill_params)

      if @skill.save
        redirect_to @skill, notice: 'Skill was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /skills/1
    def update
      if @skill.update(skill_params)
        redirect_to @skill, notice: 'Skill was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /skills/1
    def destroy
      @skill.destroy
      redirect_to skills_url, notice: 'Skill was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_skill
        @skill = current_user.skills.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def skill_params
        params.require(:skill).permit(:name, :first_used, :last_used, :proficiency, :active, :order, :user_id)
      end
  end
end

app/controllers/oluprofile/user_sessions_controller.rb
module Oluprofile
  class UserSessionsController < ApplicationController
    skip_before_action :require_login, except: [:destroy]

    def new
      @user = Oluprofile::User.new
    end

    def create
      if @user = login(params[:email], params[:password])
        redirect_back_or_to(:users, notice: 'Login successful')
      else
        flash.now[:alert] = 'Login failed'
        render action: 'new'
      end
    end

    def destroy
      logout
      redirect_to(:users, notice: 'Logged out!')
    end
  end
end

app/controllers/oluprofile/users_controller.rb
module Oluprofile
  class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login, only: [:new, :create]

    # GET /users
    def index
      @users = Oluprofile::User.all
    end

    # GET /users/1
    def show
    end

    # GET /users/new
    def new
      @user = Oluprofile::User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    def create
      @user = Oluprofile::User.new(user_params)

      if @user.save
        redirect_to :users, notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = Oluprofile::User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :description, :phone_number, :location)
      end
  end
end

app/helpers/oluprofile/application_helper.rb
module Oluprofile
  module ApplicationHelper
  end
end

app/helpers/oluprofile/skills_helper.rb
module Oluprofile
  module SkillsHelper
  end
end

app/helpers/oluprofile/user_sessions_helper.rb
module Oluprofile
  module UserSessionsHelper
  end
end

app/helpers/oluprofile/users_helper.rb
module Oluprofile
  module UsersHelper
  end
end

app/views/layouts/oluprofile/_env.html.erb
<a href="https://www.github.com/odinsride/oluprofile" target="_blank"><span class="red white-text" style="padding: 10px; border-radius: 50px"><%= rails_env %></span></a>

app/views/layouts/oluprofile/_login.html.erb
    <li><%= link_to "Register", new_user_path %></li>
    <li><%= link_to "Login", :login %></li>

app/views/layouts/oluprofile/_navbar.html.erb
<ul class="sidenav sidenav-fixed z-depth-2">
  <li class="ob-sidenav-header ob-primary">
    <div class="row">
      <div class="col s12 center-align">
        <%= link_to root_path do %><h3 class="white-text">oluprofile</h3><% end %>
        <%= render :partial => "layouts/oluprofile/env" if rails_env.present? %>
        <% if current_user %>
          <span class="btn-flat white-text"><%= current_user.email %></span>
        <% end %>
      </div>
    </div>
  </li>

  <%= render :partial => "layouts/oluprofile/navlinks" if current_user %>
  <%= render :partial => "layouts/oluprofile/login" unless current_user %>

</ul>

app/views/layouts/oluprofile/_navlinks.html.erb
    <li><%= link_to "Skills", skills_path %></li>
    <li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
    <li><%= link_to "Logout", :logout, method: :post %></li>

app/views/layouts/oluprofile/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>oluprofile</title>    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'oluprofile/application', media: 'all' %>
    <%= javascript_include_tag 'oluprofile/application' %>
  </head>

  <body>

    <header>
      <%= render "layouts/oluprofile/navbar" %>
    </header>

    <main role="main">

      <div class="container">
        <%= yield %>
      </div>

      <% flash.each do |message_type, message| %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
      <% end %>

    </main>

  </body>

</html>

app/views/oluprofile/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :first_used %>
    <%= form.number_field :first_used %>
  </div>

  <div class="field">
    <%= form.label :last_used %>
    <%= form.number_field :last_used %>
  </div>

  <div class="field">
    <%= form.label :proficiency %>
    <%= form.number_field :proficiency %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oluprofile/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/oluprofile/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First used</th>
      <th>Last used</th>
      <th>Proficiency</th>
      <th>Active</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.first_used %></td>
        <td><%= skill.last_used %></td>
        <td><%= skill.proficiency %></td>
        <td><%= skill.active %></td>
        <td><%= skill.order %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/oluprofile/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/oluprofile/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>First used:</strong>
  <%= @skill.first_used %>
</p>

<p>
  <strong>Last used:</strong>
  <%= @skill.last_used %>
</p>

<p>
  <strong>Proficiency:</strong>
  <%= @skill.proficiency %>
</p>

<p>
  <strong>Active:</strong>
  <%= @skill.active %>
</p>

<p>
  <strong>Order:</strong>
  <%= @skill.order %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

app/views/oluprofile/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>

  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div class="actions">
    <%= submit_tag "Login" %>
  </div>

<% end %>

app/views/oluprofile/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/oluprofile/user_sessions/create.html.erb</p>

app/views/oluprofile/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/oluprofile/user_sessions/destroy.html.erb</p>

app/views/oluprofile/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/oluprofile/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :email %>

  <%= f.input :password %>

  <%= f.input :password_confirmation %>

  <%= f.input :first_name %>

  <%= f.input :last_name %>
  
  <%= f.input :description %>

  <%= f.input :phone_number %>

  <%= f.input :location %>
  
  <%= f.button :submit %>
  
<% end %>

app/views/oluprofile/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/oluprofile/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Description</th>
      <th>Phone number</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.description %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/oluprofile/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/oluprofile/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>